### ISSUE TITLE
Can we get this pushed up to rubygems as a new gem?

### ISSUE THREAD

**Issue by toddnestor** [blueprinter-ruby/blueprinter#1]
Hello, I work at RaiseMe (www.raise.me), we had started migrating from ActiveModel::Serializer to Blueprinter a year or so ago, was disappointed to learn recently that Blueprinter is not really being maintained anymore.

I would love to join you as a maintainer for this new fork and help get blueprinter updated and ensure it works with the latest ruby versions (perhaps it already does, I'm going to be testing soon).

We are so far along in our migration process that I don't want us to change to yet another library, so if we can get this new fork pushed as a new gem and start maintaining it then we will be set up to more confidently complete the migration work in our own codebase.

Let me know your thoughts.  I came across this fork from where you had linked to it on the original blueprinter repo's issues.

**Comment by ritikesh** [comment]
Hey @toddnestor, apologies for the delayed response. I was just waiting to see if the original maintainers add anything on the issue you've just mentioned. Since there has been no action yet from their side, I plan on using the next week to setup this repository as the alternative blueprinter. Pushing to rubygems and updating readme would be the first steps towards that goal. 

Post that, I'll start accepting PRs and respond to issues and eventually allow more maintainers to the project based on the contributions made - the delay in adding more maintainers would also allow me to setup some basic processes around the project as well.

**Comment by ritikesh** [comment]
Apologies for the delay in making this happen. Have released version [1.0.0](https://rubygems.org/gems/blueprinter-rb) to rubygems 🎉.

**Comment by toddnestor** [comment]
Thank you @ritikesh!

**Comment by filipegiusti** [comment]
Thanks @ritikesh, I'm proposing internally that we shift to this one.

**Comment by filipegiusti** [comment]
I added it to https://github.com/rubytoolbox/catalog/pull/725
